### ISSUE TITLE
az --version tells users to update their config without explaining what to do

### ISSUE THREAD

**Issue by brycem** [MicrosoftDocs/azure-docs-cli#1341]
az --version tells users to update their config without explaining what to do - On my Win10 machine with the latest AzCLI v2.0.59 installed (today), tells me to consider updating my CLI installation but doesn't provide any guidance on what to do next.  The MSI is already at latest version

D:\Repos\BAG>az --version  (#656)
azure-cli                         2.0.59 *

>   <snipped a number of up to date* and out of date commands and extensions>

You have 14 updates available. **Consider updating your CLI installation.**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b233e045-b444-e6d9-7893-36a72ee4a70b
* Version Independent ID: f2c47d3a-4976-ebe4-e732-e7c18dd4bed8
* Content: [Overview of the Azure CLI](https://docs.microsoft.com/en-us/cli/azure/?view=azure-cli-latest#feedback)
* Content Source: [docs-ref-conceptual/index.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/index.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@tjprescott Does this seem like a product bug to you? I wasn't aware that `az --version` made a phone-home call to see if there were any available updates.

**Comment by tjprescott** [comment]
It is not a bug. We have no idea how people initially installed the CLI and thus can't direct them how to update their installation.  The latest release is 2.0.60.

**Comment by sptramer** [comment]
@brycem As Travis says, this is an accurate message based on the latest available version and users can't be directed how to reinstall based on not knowing their initial installation method. New releases are put out every two weeks, so update regularly by reinstalling from the latest MSI. Follow the [Update on Windows](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest#install-or-update) instructions.

**Comment by tjprescott** [comment]
That being said, we have discussed internally our desire to be able to "tag" the installation so it can recommend the right way to update, but it would be further down the road. Our current goal was simply to make users aware that an update was available.

**Comment by miguelmorin** [comment]
I am on `macOS`, updated with `brew update && brew upgrade azure-cli` and I kept getting the same message. I updated with:

```bash
brew uninstall azure-cli
brew update
brew upgrade
brew cleanup
brew install azure-cli
```

and I am still getting the error:

```
$ az --version
azure-cli                         2.0.64 *

acr                                2.2.6 *
...
You have 25 updates available. Consider updating your CLI installation.
```

**Comment by uc-msft** [comment]
> I am on `macOS`, updated with `brew update && brew upgrade azure-cli` and I kept getting the same message. I updated with:
> 
> ```shell
> brew uninstall azure-cli
> brew update
> brew upgrade
> brew cleanup
> brew install azure-cli
> ```
> 
> and I am still getting the error:
> 
> ```
> $ az --version
> azure-cli                         2.0.64 *
> 
> acr                                2.2.6 *
> ...
> You have 25 updates available. Consider updating your CLI installation.
> ```

I have the same issue on a brand new install on macOS. I tried uninstall & install too.

**Comment by rodbutters** [comment]
Same here - fresh install via brew exactly described on https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-macos?view=azure-cli-latest. Python 3.7.3.

**Comment by uc-msft** [comment]
I was able to do brew update & upgrade today to get the latest now 2.0.66 version.

**Comment by miguelmorin** [comment]
Same here, I am now on 2.0.66 and see `Your CLI is up-to-date.`

**Comment by rido-min** [comment]
I just installed the latest and now I have 2.0.67 but still see the message `Consider updating your CLI installation.`

@sptramer the [link]( https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest#install-or-update
) you provided in your [your comment](https://github.com/MicrosoftDocs/azure-docs-cli/issues/1341#issuecomment-474451043) does not include any update instructions.

**Comment by sptramer** [comment]
@rido-min New versions are released every other Tuesday. You may have installed in the period where an update was being pushed.

All platform [install instructions](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest) contain information on updating.

**Comment by rido-min** [comment]
The point of this issue is that I installed the latest 2.0.67 but I still see `You have 5 updates available. Consider updating your CLI installation.`

... and don't know how to update. The install instructions redirect to the same MSI I just installed.

**Comment by ChristianBeier** [comment]
I just updated azure-cli to 2.0.68 (currently latest) on Windows and run into the update available message. On Debian@WSL everything is fine.
`PS C:\Users\me> az --version                                                                                                                                                                                                                                                                                            azure-cli                         2.0.68

command-modules-nspkg               **2.0.2 ***
core                              2.0.68
nspkg                              3.0.4
telemetry                          1.0.3

Extensions:
azure-cli-iot-ext                  0.7.1
eventgrid                          0.4.3

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\me\.azure\cliextensions'

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


You have 1 updates available. Consider updating your CLI installation.`

The asterisk seems to indicate command-modules-nspkg is out of date and indeed there is version 2.0.3 listed on https://pypi.org/project/azure-cli-command-modules-nspkg/ and also installed under Debian@WSL
Unfortunately it is not clear how to update the package as it should be provided by azure-cli and _"This package is not intended to be installed directly by the end user."_

**Comment by ChristianBeier** [comment]
On Windows I just updated azure-cli to version 2.0.68 (currently latest) and also got the message. It seems that in my case _command-modules-nspkg_ is not updated to latest version - indicated by asterisk * behind version number. Reboot and repair also didn't help and as https://pypi.org/project/azure-cli-command-modules-nspkg/ states _"This package is not intended to be installed directly by the end user."_ states, I see no possibility to update besides waiting for next azure-cli version.
On Debian@WLS everything is fine. I think it does not harm to ignore the warning, at least I could not recognize a negative effect.

**Comment by tmdevries** [comment]
> On Windows I just updated azure-cli to version 2.0.68 (currently latest) and also got the message. It seems that in my case _command-modules-nspkg_ is not updated to latest version - indicated by asterisk * behind version number. Reboot and repair also didn't help and as https://pypi.org/project/azure-cli-command-modules-nspkg/ states _"This package is not intended to be installed directly by the end user."_ states, I see no possibility to update besides waiting for next azure-cli version.
> On Debian@WLS everything is fine. I think it does not harm to ignore the warning, at least I could not recognize a negative effect.

I am having this issue on Win10 as well. The version of command-modules-nspkg is showing to be 2.0.2. It's the only module that has an asterisk next to its version.

**Comment by boelaars** [comment]
@sptramer @tjprescott This is a very clear bug. Just because there is not yet a clear path to solve it that doesn't negate this fact of course. At this very moment https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest states "The current version of the CLI is **2.0.68**." and provides the corresponding version's MSI. Installing it and then running "az --version" says "azure-cli 2.0.68" but also the message "You have 1 updates available. Consider updating your CLI installation."

This issue should be re-opened.

**Comment by bigdatamoore** [comment]
I am also getting this message when I enter az --version.  Even though I just did a fresh install of az, it is telling me that there are 15 updates.

**Comment by IvanFarkas** [comment]
ditto

**Comment by pedroneil** [comment]
I have installed 2.0.68 msi from 2.0.60 and az --version suggests that I should update modules that have been installed by the MSI; shouldn't your comparison be against the modules installed by the MSI and not those available on the TinTinET?

az --version
azure-cli                         2.0.68 *

command-modules-nspkg               2.0.2 *
core                              2.0.68 *
nspkg                              3.0.4
telemetry                          1.0.3

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\username\.azure\cliextensions'

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


You have 3 updates available. Consider updating your CLI installation.

C:\WINDOWS\system32>where python
INFO: Could not find files for the given pattern(s).

**Comment by sptramer** [comment]
There seems to have been a bug in a previous release which was causing the mistaken `az --version` message about requiring an update. It should be fixed in today's 2.0.69 release.

**Comment by pedroneil** [comment]
Thank you for the update

**Comment by melonrush13** [comment]
I'm on version 2.0.69 and I am still getting the message of 'You have 2 updates available. Consider updating your CLI installation.' I do a az --version and it says I am up to date.

**Comment by shahzzzam** [comment]
Ditto!

```
az --version
azure-cli                         2.0.64 *

acr                                2.2.6 *
acs                                2.4.1 *
advisor                            2.0.0 *
ams                                0.4.5 *
appservice                        0.2.19 *
backup                             1.2.4 *
batch                              4.0.1 *
batchai                            0.4.8 *
billing                            0.2.1 *
botservice                         0.2.0 *
cdn                                0.2.3 *
cloud                              2.1.1
cognitiveservices                  0.2.5 *
command-modules-nspkg               2.0.2 *
configure                         2.0.23 *
consumption                        0.4.2 *
container                         0.3.16 *
core                              2.0.64 *
cosmosdb                          0.2.10 *
deploymentmanager                  0.1.0 *
dla                                0.2.5 *
dls                                0.1.9 *
dms                                0.1.3 *
eventgrid                          0.2.3 *
eventhubs                          0.3.5 *
extension                          0.2.5
feedback                           2.2.1
find                               0.3.2 *
hdinsight                          0.3.3 *
interactive                        0.4.3 *
iot                                0.3.8 *
iotcentral                         0.1.6 *
keyvault                          2.2.15 *
kusto                              0.2.2 *
lab                                0.1.7 *
maps                               0.3.4 *
monitor                           0.2.13 *
network                            2.4.0 *
nspkg                              3.0.3 *
policyinsights                     0.1.3 *
privatedns                         1.0.0 *
profile                            2.1.5
rdbms                             0.3.10 *
redis                              0.4.2 *
relay                              0.1.4 *
reservations                       0.4.2 *
resource                          2.1.14 *
role                               2.6.1 *
search                             0.1.1 *
security                           0.1.1 *
servicebus                         0.3.5 *
servicefabric                     0.1.18 *
signalr                            1.0.0 *
sql                                2.2.3 *
sqlvm                              0.1.1 *
storage                            2.4.1 *
telemetry                          1.0.2 *
vm                                2.2.20 *

Python location '/usr/bin/python'
Extensions directory '/home/samashah/.azure/cliextensions'

Python (Linux) 2.7.15+ (default, Nov 27 2018, 23:36:35) 
[GCC 7.3.0]

Legal docs and information: aka.ms/AzureCliLegal


You have 55 updates available. Consider updating your CLI installation.
```

I follow the upgrade instructions:

```
$sudo apt-get update && sudo apt-get install --only-upgrade -y azure-cli

...
Reading state information... Done
azure-cli is already the newest version (2.0.70-1~bionic).
0 upgraded, 0 newly installed, 0 to remove and 26 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
...
```

**Comment by Singh-Prateek** [comment]
still getting this error without any direction. 
> azure-cli                         2.0.69 *                                                                                                                  
> command-modules-nspkg               2.0.3
> core                              2.0.69 *
> nspkg                              3.0.4
> telemetry                          1.0.3
> 
> Extensions:
> azure-devops                      0.11.0
> 
> Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
> Extensions directory 'C:\Users\xxxxxx\.azure\cliextensions'
> 
> Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]
> 
> **You have 2 updates available. Consider updating your CLI installation.**

**Comment by sptramer** [comment]
I've made the engineering team aware that this message can be confusing since it doesn't include directions on how to update. Thanks for everyone's feedback.

**Comment by Dolcekar** [comment]
Just so you are aware, the 2.0.70 version resolves this problem. At least in my os it does, I have Windows 7 (don't make fun of me ^.^)
```
az --version
azure-cli                         2.0.70

command-modules-nspkg               2.0.3
core                              2.0.70
nspkg                              3.0.4
telemetry                          1.0.3

Extensions:
azure-cli-iot-ext                  0.7.0

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\RIC1CCox\.azure\cliextensions'

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32
 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

**Comment by WDMichael** [comment]
still not fixed ... I have version 2.0.70...

az --version
azure-cli                         2.0.70 *

command-modules-nspkg               2.0.3
core                              2.0.70 *
nspkg                              3.0.4
telemetry                          1.0.3

Python location '/usr/local/Cellar/azure-cli/2.0.70/libexec/bin/python'
Extensions directory '/Users/userid/.azure/cliextensions'

Python (Darwin) 3.7.4 (default, Jul  9 2019, 18:13:23) 
[Clang 10.0.1 (clang-1001.0.46.4)]

Legal docs and information: aka.ms/AzureCliLegal

You have 2 updates available. Consider updating your CLI installation.

**Comment by ChristianBeier** [comment]
> azure-cli 2.0.70 *
...indicates that there is a newer version of azure-cli, maybe try an update of your CLI installation on your OS ;)
Everything works now for me on Windows and Linux (Debian WLS) as expected

**Comment by SeaDude** [comment]
Users could really benefit from the command `az --upgrade`. There is probably a good reason why this is omitted, but nonetheless thought I'd mention it in this thread.
